
### TESTING THE API


###user
###get user 

GET http://localhost:8000/api/v1/users
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJva2E3MzYyQGdtYWlsLmNvbSIsImlhdCI6MTc2MjY5MDQ0MSwiZXhwIjoxNzYyNzc2ODQxfQ.sPWKkm5PjdOhWFWqE1UlZBM-rB7frngJHI7rcklAEgY
###
POST http://localhost:8000/api/v1/users
Content-Type: application/json

{
    "name" : "suman",
    "email" : "roka756@gmail.com",
    "password" : "12345"
}
###

###LOGIN user 
POST http://localhost:8000/api/v1/users/login
Content-Type: application/json

{

    "email" : "roka7362@gmail.com",
    "password" : "12345"
}

###

###
POST http://localhost:8000/api/v1/transactions
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJva2E3MzYyQGdtYWlsLmNvbSIsImlhdCI6MTc2MzAzMjk5NiwiZXhwIjoxNzYzMTE5Mzk2fQ.LPOWx_2jEJyTCfdoWzFE9QX5_vft-1cAa9Ty-LfdqFg

{
    "type":"income",
    "title":"salary",
    "amount":"3333",
    "tDate":"12-11-2025"
}


###
// getting all the transaction from the database
GET  http://localhost:8000/api/v1/transactions
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJva2E3MzYyQGdtYWlsLmNvbSIsImlhdCI6MTc2MzAzMjk5NiwiZXhwIjoxNzYzMTE5Mzk2fQ.LPOWx_2jEJyTCfdoWzFE9QX5_vft-1cAa9Ty-LfdqFg

### delete 
DELETE  http://localhost:8000/api/v1/transactions
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJva2E3MzYyQGdtYWlsLmNvbSIsImlhdCI6MTc2NDAzNTM5OCwiZXhwIjoxNzY0MTIxNzk4fQ.i2akP35HdqPBeX1aYAQTlCKJdFNx2HA07GWCTwlnWok

["6915bfead6fa601a4b52a554","6917371b519c9af5272eea6e"]

